import type { Metadata } from "next";
import "./globals.css";

import { Moul, Inter } from "next/font/google";

export const moul = Moul({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-moul",
});

export const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${moul.variable}`}>{children}</body>
    </html>
  );
}
